repos:
  - repo: local
    hooks:
      - id: prep
        name: prepare terraform provider
        entry: bash -c 'task prep -f'
        language: system
        types: ["go"]
        files: main.go|forwardemail\/.*
        pass_filenames: false
